[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/v1/tasks"
  to = "/.netlify/functions/tasks"
  status = 200
  force = true

[[redirects]]
  from = "/svcdesk/v1/tasks"
  to = "/.netlify/functions/tasks"
  status = 200
  force = true

[[redirects]]
  from = "/v1/callbacks/scheduled"
  to = "/.netlify/functions/tasks"
  status = 200
  force = true
